// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/food/raw/raw.proto

package go_micro_srv_dietetics

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RawFood struct {
	Code                 string       `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Group                string       `protobuf:"bytes,2,opt,name=Group,proto3" json:"Group,omitempty"`
	Name                 string       `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Varietie             string       `protobuf:"bytes,4,opt,name=Varietie,proto3" json:"Varietie,omitempty"`
	SampleQuantity       float32      `protobuf:"fixed32,5,opt,name=SampleQuantity,proto3" json:"SampleQuantity,omitempty"`
	SampleUnit           string       `protobuf:"bytes,6,opt,name=SampleUnit,proto3" json:"SampleUnit,omitempty"`
	Nutritions           []*Nutrition `protobuf:"bytes,7,rep,name=Nutritions,proto3" json:"Nutritions,omitempty"`
	Tags                 string       `protobuf:"bytes,8,opt,name=Tags,proto3" json:"Tags,omitempty"`
	Status               string       `protobuf:"bytes,9,opt,name=Status,proto3" json:"Status,omitempty"`
	LastModified         string       `protobuf:"bytes,10,opt,name=LastModified,proto3" json:"LastModified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RawFood) Reset()         { *m = RawFood{} }
func (m *RawFood) String() string { return proto.CompactTextString(m) }
func (*RawFood) ProtoMessage()    {}
func (*RawFood) Descriptor() ([]byte, []int) {
	return fileDescriptor_raw_b7dae7e4d8070cae, []int{0}
}
func (m *RawFood) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawFood.Unmarshal(m, b)
}
func (m *RawFood) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawFood.Marshal(b, m, deterministic)
}
func (dst *RawFood) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawFood.Merge(dst, src)
}
func (m *RawFood) XXX_Size() int {
	return xxx_messageInfo_RawFood.Size(m)
}
func (m *RawFood) XXX_DiscardUnknown() {
	xxx_messageInfo_RawFood.DiscardUnknown(m)
}

var xxx_messageInfo_RawFood proto.InternalMessageInfo

func (m *RawFood) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RawFood) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *RawFood) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RawFood) GetVarietie() string {
	if m != nil {
		return m.Varietie
	}
	return ""
}

func (m *RawFood) GetSampleQuantity() float32 {
	if m != nil {
		return m.SampleQuantity
	}
	return 0
}

func (m *RawFood) GetSampleUnit() string {
	if m != nil {
		return m.SampleUnit
	}
	return ""
}

func (m *RawFood) GetNutritions() []*Nutrition {
	if m != nil {
		return m.Nutritions
	}
	return nil
}

func (m *RawFood) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *RawFood) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *RawFood) GetLastModified() string {
	if m != nil {
		return m.LastModified
	}
	return ""
}

type Nutrition struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Quantity             float32  `protobuf:"fixed32,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Aprox                float32  `protobuf:"fixed32,4,opt,name=Aprox,proto3" json:"Aprox,omitempty"`
	Unit                 string   `protobuf:"bytes,5,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Group                string   `protobuf:"bytes,6,opt,name=Group,proto3" json:"Group,omitempty"`
	Tags                 string   `protobuf:"bytes,7,opt,name=Tags,proto3" json:"Tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nutrition) Reset()         { *m = Nutrition{} }
func (m *Nutrition) String() string { return proto.CompactTextString(m) }
func (*Nutrition) ProtoMessage()    {}
func (*Nutrition) Descriptor() ([]byte, []int) {
	return fileDescriptor_raw_b7dae7e4d8070cae, []int{1}
}
func (m *Nutrition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nutrition.Unmarshal(m, b)
}
func (m *Nutrition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nutrition.Marshal(b, m, deterministic)
}
func (dst *Nutrition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nutrition.Merge(dst, src)
}
func (m *Nutrition) XXX_Size() int {
	return xxx_messageInfo_Nutrition.Size(m)
}
func (m *Nutrition) XXX_DiscardUnknown() {
	xxx_messageInfo_Nutrition.DiscardUnknown(m)
}

var xxx_messageInfo_Nutrition proto.InternalMessageInfo

func (m *Nutrition) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Nutrition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Nutrition) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Nutrition) GetAprox() float32 {
	if m != nil {
		return m.Aprox
	}
	return 0
}

func (m *Nutrition) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Nutrition) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Nutrition) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

type AddNutritionRequest struct {
	Query                []*PairRequest `protobuf:"bytes,1,rep,name=Query,proto3" json:"Query,omitempty"`
	Nutrition            *Nutrition     `protobuf:"bytes,2,opt,name=nutrition,proto3" json:"nutrition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddNutritionRequest) Reset()         { *m = AddNutritionRequest{} }
func (m *AddNutritionRequest) String() string { return proto.CompactTextString(m) }
func (*AddNutritionRequest) ProtoMessage()    {}
func (*AddNutritionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_raw_b7dae7e4d8070cae, []int{2}
}
func (m *AddNutritionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNutritionRequest.Unmarshal(m, b)
}
func (m *AddNutritionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNutritionRequest.Marshal(b, m, deterministic)
}
func (dst *AddNutritionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNutritionRequest.Merge(dst, src)
}
func (m *AddNutritionRequest) XXX_Size() int {
	return xxx_messageInfo_AddNutritionRequest.Size(m)
}
func (m *AddNutritionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNutritionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNutritionRequest proto.InternalMessageInfo

func (m *AddNutritionRequest) GetQuery() []*PairRequest {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *AddNutritionRequest) GetNutrition() *Nutrition {
	if m != nil {
		return m.Nutrition
	}
	return nil
}

type DeleteNutritionRequest struct {
	RootSelector         []*PairRequest `protobuf:"bytes,1,rep,name=RootSelector,proto3" json:"RootSelector,omitempty"`
	ChildSelector        []*PairRequest `protobuf:"bytes,2,rep,name=ChildSelector,proto3" json:"ChildSelector,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteNutritionRequest) Reset()         { *m = DeleteNutritionRequest{} }
func (m *DeleteNutritionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNutritionRequest) ProtoMessage()    {}
func (*DeleteNutritionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_raw_b7dae7e4d8070cae, []int{3}
}
func (m *DeleteNutritionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNutritionRequest.Unmarshal(m, b)
}
func (m *DeleteNutritionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNutritionRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteNutritionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNutritionRequest.Merge(dst, src)
}
func (m *DeleteNutritionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNutritionRequest.Size(m)
}
func (m *DeleteNutritionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNutritionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNutritionRequest proto.InternalMessageInfo

func (m *DeleteNutritionRequest) GetRootSelector() []*PairRequest {
	if m != nil {
		return m.RootSelector
	}
	return nil
}

func (m *DeleteNutritionRequest) GetChildSelector() []*PairRequest {
	if m != nil {
		return m.ChildSelector
	}
	return nil
}

type GetRawFoodRequests struct {
	Limit                int32          `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Skip                 int32          `protobuf:"varint,2,opt,name=Skip,proto3" json:"Skip,omitempty"`
	RawFoods             []*PairRequest `protobuf:"bytes,3,rep,name=RawFoods,proto3" json:"RawFoods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRawFoodRequests) Reset()         { *m = GetRawFoodRequests{} }
func (m *GetRawFoodRequests) String() string { return proto.CompactTextString(m) }
func (*GetRawFoodRequests) ProtoMessage()    {}
func (*GetRawFoodRequests) Descriptor() ([]byte, []int) {
	return fileDescriptor_raw_b7dae7e4d8070cae, []int{4}
}
func (m *GetRawFoodRequests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRawFoodRequests.Unmarshal(m, b)
}
func (m *GetRawFoodRequests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRawFoodRequests.Marshal(b, m, deterministic)
}
func (dst *GetRawFoodRequests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRawFoodRequests.Merge(dst, src)
}
func (m *GetRawFoodRequests) XXX_Size() int {
	return xxx_messageInfo_GetRawFoodRequests.Size(m)
}
func (m *GetRawFoodRequests) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRawFoodRequests.DiscardUnknown(m)
}

var xxx_messageInfo_GetRawFoodRequests proto.InternalMessageInfo

func (m *GetRawFoodRequests) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetRawFoodRequests) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetRawFoodRequests) GetRawFoods() []*PairRequest {
	if m != nil {
		return m.RawFoods
	}
	return nil
}

type GetRawFoodRequest struct {
	RawFoods             []*PairRequest `protobuf:"bytes,1,rep,name=RawFoods,proto3" json:"RawFoods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRawFoodRequest) Reset()         { *m = GetRawFoodRequest{} }
func (m *GetRawFoodRequest) String() string { return proto.CompactTextString(m) }
func (*GetRawFoodRequest) ProtoMessage()    {}
func (*GetRawFoodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_raw_b7dae7e4d8070cae, []int{5}
}
func (m *GetRawFoodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRawFoodRequest.Unmarshal(m, b)
}
func (m *GetRawFoodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRawFoodRequest.Marshal(b, m, deterministic)
}
func (dst *GetRawFoodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRawFoodRequest.Merge(dst, src)
}
func (m *GetRawFoodRequest) XXX_Size() int {
	return xxx_messageInfo_GetRawFoodRequest.Size(m)
}
func (m *GetRawFoodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRawFoodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRawFoodRequest proto.InternalMessageInfo

func (m *GetRawFoodRequest) GetRawFoods() []*PairRequest {
	if m != nil {
		return m.RawFoods
	}
	return nil
}

type RawFoodsResponse struct {
	RawFoodRes           []*RawFood `protobuf:"bytes,1,rep,name=RawFoodRes,proto3" json:"RawFoodRes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RawFoodsResponse) Reset()         { *m = RawFoodsResponse{} }
func (m *RawFoodsResponse) String() string { return proto.CompactTextString(m) }
func (*RawFoodsResponse) ProtoMessage()    {}
func (*RawFoodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_raw_b7dae7e4d8070cae, []int{6}
}
func (m *RawFoodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawFoodsResponse.Unmarshal(m, b)
}
func (m *RawFoodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawFoodsResponse.Marshal(b, m, deterministic)
}
func (dst *RawFoodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawFoodsResponse.Merge(dst, src)
}
func (m *RawFoodsResponse) XXX_Size() int {
	return xxx_messageInfo_RawFoodsResponse.Size(m)
}
func (m *RawFoodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawFoodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawFoodsResponse proto.InternalMessageInfo

func (m *RawFoodsResponse) GetRawFoodRes() []*RawFood {
	if m != nil {
		return m.RawFoodRes
	}
	return nil
}

type PairRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairRequest) Reset()         { *m = PairRequest{} }
func (m *PairRequest) String() string { return proto.CompactTextString(m) }
func (*PairRequest) ProtoMessage()    {}
func (*PairRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_raw_b7dae7e4d8070cae, []int{7}
}
func (m *PairRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairRequest.Unmarshal(m, b)
}
func (m *PairRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairRequest.Marshal(b, m, deterministic)
}
func (dst *PairRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairRequest.Merge(dst, src)
}
func (m *PairRequest) XXX_Size() int {
	return xxx_messageInfo_PairRequest.Size(m)
}
func (m *PairRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PairRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PairRequest proto.InternalMessageInfo

func (m *PairRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PairRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GeneralResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Detail               string   `protobuf:"bytes,3,opt,name=Detail,proto3" json:"Detail,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralResponse) Reset()         { *m = GeneralResponse{} }
func (m *GeneralResponse) String() string { return proto.CompactTextString(m) }
func (*GeneralResponse) ProtoMessage()    {}
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_raw_b7dae7e4d8070cae, []int{8}
}
func (m *GeneralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralResponse.Unmarshal(m, b)
}
func (m *GeneralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralResponse.Marshal(b, m, deterministic)
}
func (dst *GeneralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralResponse.Merge(dst, src)
}
func (m *GeneralResponse) XXX_Size() int {
	return xxx_messageInfo_GeneralResponse.Size(m)
}
func (m *GeneralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralResponse proto.InternalMessageInfo

func (m *GeneralResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GeneralResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GeneralResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *GeneralResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*RawFood)(nil), "go.micro.srv.dietetics.RawFood")
	proto.RegisterType((*Nutrition)(nil), "go.micro.srv.dietetics.Nutrition")
	proto.RegisterType((*AddNutritionRequest)(nil), "go.micro.srv.dietetics.AddNutritionRequest")
	proto.RegisterType((*DeleteNutritionRequest)(nil), "go.micro.srv.dietetics.DeleteNutritionRequest")
	proto.RegisterType((*GetRawFoodRequests)(nil), "go.micro.srv.dietetics.GetRawFoodRequests")
	proto.RegisterType((*GetRawFoodRequest)(nil), "go.micro.srv.dietetics.GetRawFoodRequest")
	proto.RegisterType((*RawFoodsResponse)(nil), "go.micro.srv.dietetics.RawFoodsResponse")
	proto.RegisterType((*PairRequest)(nil), "go.micro.srv.dietetics.PairRequest")
	proto.RegisterType((*GeneralResponse)(nil), "go.micro.srv.dietetics.GeneralResponse")
}

func init() { proto.RegisterFile("proto/food/raw/raw.proto", fileDescriptor_raw_b7dae7e4d8070cae) }

var fileDescriptor_raw_b7dae7e4d8070cae = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x9d, 0x3a, 0x6d, 0xa6, 0xbf, 0x2c, 0x28, 0xb2, 0x72, 0x80, 0x62, 0x24, 0x08, 0x20,
	0xb9, 0x52, 0x11, 0x07, 0x4e, 0x55, 0xd4, 0x8a, 0xa8, 0xa2, 0x54, 0xd4, 0x69, 0x2b, 0x38, 0x70,
	0x58, 0xb2, 0xd3, 0xb2, 0xe0, 0x64, 0xcd, 0xee, 0xba, 0x25, 0x27, 0x9e, 0x81, 0x67, 0xe0, 0x8a,
	0xc4, 0x1b, 0xf0, 0x6c, 0xc8, 0xeb, 0xdf, 0xa4, 0x8d, 0x6a, 0x10, 0x87, 0x48, 0x33, 0x93, 0xfd,
	0xbe, 0x9d, 0xf9, 0x26, 0xdf, 0x06, 0xdc, 0x48, 0x0a, 0x2d, 0xb6, 0xce, 0x84, 0x60, 0x5b, 0x92,
	0x5e, 0x26, 0x1f, 0xdf, 0x94, 0x48, 0xfb, 0x5c, 0xf8, 0x23, 0x3e, 0x94, 0xc2, 0x57, 0xf2, 0xc2,
	0x67, 0x1c, 0x35, 0x6a, 0x3e, 0x54, 0xde, 0x6f, 0x1b, 0x16, 0x03, 0x7a, 0xf9, 0x52, 0x08, 0x46,
	0x08, 0x2c, 0xec, 0x0a, 0x86, 0xae, 0xb5, 0x69, 0x75, 0x5b, 0x81, 0x89, 0xc9, 0x1d, 0x70, 0xfa,
	0x52, 0xc4, 0x91, 0x6b, 0x9b, 0x62, 0x9a, 0x24, 0x27, 0x0f, 0xe9, 0x08, 0xdd, 0x46, 0x7a, 0x32,
	0x89, 0x49, 0x07, 0x96, 0x4e, 0xa9, 0xe4, 0xa8, 0x39, 0xba, 0x0b, 0xa6, 0x5e, 0xe4, 0xe4, 0x21,
	0xac, 0x0d, 0xe8, 0x28, 0x0a, 0xf1, 0x28, 0xa6, 0x63, 0xcd, 0xf5, 0xc4, 0x75, 0x36, 0xad, 0xae,
	0x1d, 0xcc, 0x54, 0xc9, 0x5d, 0x80, 0xb4, 0x72, 0x32, 0xe6, 0xda, 0x6d, 0x1a, 0x96, 0x4a, 0x85,
	0xf4, 0x00, 0x0e, 0x63, 0x2d, 0xb9, 0xe6, 0x62, 0xac, 0xdc, 0xc5, 0xcd, 0x46, 0x77, 0x79, 0xfb,
	0xbe, 0x7f, 0xfd, 0x68, 0x7e, 0x71, 0x32, 0xa8, 0x80, 0x92, 0xd6, 0x8f, 0xe9, 0xb9, 0x72, 0x97,
	0xd2, 0xd6, 0x93, 0x98, 0xb4, 0xa1, 0x39, 0xd0, 0x54, 0xc7, 0xca, 0x6d, 0x99, 0x6a, 0x96, 0x11,
	0x0f, 0x56, 0x0e, 0xa8, 0xd2, 0xaf, 0x05, 0xe3, 0x67, 0x1c, 0x99, 0x0b, 0xe6, 0xdb, 0xa9, 0x9a,
	0xf7, 0xc3, 0x82, 0x56, 0x41, 0x6f, 0xd8, 0x27, 0x51, 0x21, 0x61, 0x12, 0x17, 0x62, 0xd9, 0xd3,
	0x62, 0x15, 0x52, 0x34, 0x8c, 0x14, 0x45, 0x9e, 0x48, 0xde, 0x8b, 0xa4, 0xf8, 0x6a, 0x54, 0xb4,
	0x83, 0x34, 0x49, 0x58, 0x8c, 0x28, 0x4e, 0xca, 0x62, 0xe4, 0x28, 0x96, 0xd3, 0x9c, 0x59, 0x8e,
	0x99, 0x70, 0xb1, 0x9c, 0xd0, 0xfb, 0x6e, 0xc1, 0xed, 0x1e, 0x63, 0xa5, 0x24, 0xf8, 0x25, 0x46,
	0xa5, 0xc9, 0x0b, 0x70, 0x8e, 0x62, 0x94, 0x13, 0xd7, 0x32, 0x5a, 0x3e, 0x98, 0xa7, 0xe5, 0x1b,
	0xca, 0x65, 0x86, 0x09, 0x52, 0x04, 0xd9, 0x81, 0xd6, 0x38, 0xa7, 0x33, 0xb3, 0xd5, 0x5a, 0x45,
	0x89, 0xf1, 0x7e, 0x5a, 0xd0, 0xde, 0xc3, 0x10, 0x35, 0x5e, 0x69, 0xab, 0x0f, 0x2b, 0x81, 0x10,
	0x7a, 0x80, 0x21, 0x0e, 0xb5, 0x90, 0x7f, 0xd3, 0xdd, 0x14, 0x90, 0xec, 0xc3, 0xea, 0xee, 0x47,
	0x1e, 0xb2, 0x82, 0xc9, 0xae, 0xcf, 0x34, 0x8d, 0xf4, 0xbe, 0x01, 0xe9, 0xa3, 0xce, 0xbc, 0x92,
	0x9d, 0x51, 0xc9, 0x0a, 0x0e, 0xf8, 0x88, 0x6b, 0xb3, 0x71, 0x27, 0x48, 0x93, 0x64, 0x05, 0x83,
	0xcf, 0x3c, 0x35, 0x8d, 0x13, 0x98, 0x98, 0xec, 0xc0, 0x52, 0x06, 0x56, 0x6e, 0xa3, 0x7e, 0x17,
	0x05, 0xc8, 0x3b, 0x86, 0x5b, 0x57, 0x1a, 0x98, 0x62, 0xb5, 0xfe, 0x85, 0x75, 0x00, 0x1b, 0x79,
	0x1c, 0xa0, 0x8a, 0xc4, 0x58, 0x21, 0xd9, 0x01, 0x28, 0xae, 0xc9, 0x69, 0xef, 0xcd, 0xa3, 0xcd,
	0x4f, 0x56, 0x20, 0xde, 0x73, 0x58, 0xae, 0xdc, 0x46, 0x36, 0xa0, 0xf1, 0x0a, 0x27, 0x99, 0x29,
	0x92, 0x30, 0x91, 0xed, 0x94, 0x86, 0x71, 0x6e, 0x8a, 0x34, 0xf1, 0x10, 0xd6, 0xfb, 0x38, 0x46,
	0x49, 0xc3, 0xa2, 0x95, 0x35, 0xb0, 0xf7, 0x59, 0x86, 0xb4, 0xf7, 0xcb, 0x37, 0x2a, 0x53, 0xd6,
	0xbc, 0x51, 0x6d, 0x68, 0xee, 0xa1, 0xa6, 0x3c, 0xcc, 0xde, 0xa3, 0x2c, 0xab, 0xd8, 0x7a, 0xa1,
	0x6a, 0xeb, 0xed, 0x5f, 0x8e, 0x99, 0x6f, 0x80, 0xf2, 0x82, 0x0f, 0x91, 0x9c, 0x02, 0xf4, 0x18,
	0xcb, 0x1f, 0xc1, 0x9b, 0xe6, 0xec, 0x3c, 0x9a, 0x77, 0x60, 0xb6, 0x75, 0x06, 0x2b, 0x55, 0xcb,
	0x91, 0xa7, 0xf3, 0x80, 0xd7, 0x18, 0xb3, 0xfe, 0x2d, 0x9f, 0x60, 0x7d, 0xc6, 0x44, 0xc4, 0x9f,
	0x87, 0xbd, 0xde, 0x6d, 0xf5, 0xef, 0x7a, 0x07, 0xab, 0x27, 0x11, 0xa3, 0x1a, 0xff, 0xbf, 0x58,
	0x6f, 0x01, 0xca, 0x1f, 0x37, 0x79, 0x3c, 0x1f, 0x36, 0x63, 0x80, 0xce, 0x4d, 0x2d, 0x90, 0x21,
	0x2c, 0x97, 0x28, 0x45, 0x9e, 0xd4, 0xa6, 0x56, 0x9d, 0xee, 0x0d, 0xdc, 0xa5, 0x63, 0xde, 0xc3,
	0x6a, 0x2a, 0x6e, 0x7e, 0x6b, 0x1d, 0x17, 0xd6, 0x56, 0xe7, 0x43, 0xd3, 0xfc, 0x89, 0x3f, 0xfb,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x39, 0x1e, 0x89, 0xb6, 0xe0, 0x07, 0x00, 0x00,
}
